name: Deploy Team Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Дозволяє запускати вручну через GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Дозвіл на запис для деплою
      pages: write     # Дозвіл на публікацію Pages
      id-token: write  # Дозвіл на OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Отримати всю історію комітів

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate site
        run: python generate_site.py

      - name: Test generated HTML
        run: |
          # Проста перевірка, що файл існує і не порожній
          if [ ! -s "index.html" ]; then
            echo "Error: index.html is empty or missing"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

